global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'java-services'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'notification-service:8081'
          - 'book-service:8080'
          - 'gateway:8222'
