services:
  book-service:
    build:
      context: /book-service/.
    container_name: app
    image: my-app:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

  notification-service:
    build:
      context: /notification/.
    container_name: my-notification
    image: my-notification:latest
    ports:
      - 8081:8081

  eureka-server:
    build:
      context: /eureka-server/.
    container_name: eureka-server
    image: eureka-server:latest
    ports:
      - "8761:8761"

  postgres:
    container_name: postgresql
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - 5000:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

