apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-configmap
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server-0.eureka-headless-service:8761/eureka/,http://eureka-server-1.eureka-headless-service:8761/eureka/"
