apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-map
data:
  application.properties: |
    eureka.client.service-url.defaultZone=http://eureka-service:8761/eureka/
    eureka.instance.hostname=config-server
    eureka.instance.prefer-ip-address=false
