spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service-books
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/api/books/**

            - id: book-service-auth
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/api/auth/**

            - id: book-service-authors
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/api/authors/**


server:
  port: 8222


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


app:
  jwtSecret: 5121359nWAALSJDHAKDASLKM65E2583rFxWdASDHJAJ41243SJKDSJAKDajshdjh
  jwtExpiration: 30000000
