management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service-books
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/api/books/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: bookServiceCircuitBreaker
                    fallbackUri: forward:/fallback/books
                - name: Retry
                  args:
                    retries: 3
                    methods: POST, PUT, DELETE, PATCH

            - id: book-service-auth
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/api/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: bookServiceAuthCircuitBreaker
                    fallbackUri: forward:/fallback/books
                - name: Retry
                  args:
                    retries: 3
                    methods: POST, PUT, DELETE, PATCH


            - id: book-service-authors
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/api/authors/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: bookServiceAuthorCircuitBreaker
                    fallbackUri: forward:/fallback/books
                - name: Retry
                  args:
                    retries: 3
                    methods: POST, PUT, DELETE, PATCH

resilience4j:
  bulkhead:
    instances:
      bookServiceCircuitBreaker:
        maxConcurrentCalls: 5
        maxWaitDuration: 0

server:
  port: 8222


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


app:
  jwtSecret: 5121359nWAALSJDHAKDASLKM65E2583rFxWdASDHJAJ41243SJKDSJAKDajshdjh
  jwtExpiration: 30000000
